### ISSUE TITLE
Increase tomcat's session timeout

### ISSUE THREAD

**Issue by hvge** [lime-company/powerauth-docker#1]
Currently, the session timeout is set to 1 minute (by default from Tomcat). We should increase this value for debugging purposes.

**Comment by romanstrobl** [comment]
I checked the web.xml file inside docker container for powerauth-server and the default timeout is 30 minutes in web.xml:

```xml
  <!-- You can set the default session timeout (in minutes) for all newly   -->
  <!-- created sessions by modifying the value below.                       -->

    <session-config>
        <session-timeout>30</session-timeout>
    </session-config>
```

In case 30 minutes is not long enough, what timeout do you suggest?

**Comment by petrdvorak** [comment]
We can close this issue - for some reason, the session used to be terminated after 1 minute before, but this is no longer the case...
